// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Topic                []byte   `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Record) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Record) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type PutRecordsRequest struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=Records,proto3" json:"Records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PutRecordsRequest) Reset()         { *m = PutRecordsRequest{} }
func (m *PutRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*PutRecordsRequest) ProtoMessage()    {}
func (*PutRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *PutRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRecordsRequest.Unmarshal(m, b)
}
func (m *PutRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRecordsRequest.Marshal(b, m, deterministic)
}
func (m *PutRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRecordsRequest.Merge(m, src)
}
func (m *PutRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_PutRecordsRequest.Size(m)
}
func (m *PutRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRecordsRequest proto.InternalMessageInfo

func (m *PutRecordsRequest) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type PutRecordsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRecordsResponse) Reset()         { *m = PutRecordsResponse{} }
func (m *PutRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*PutRecordsResponse) ProtoMessage()    {}
func (*PutRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *PutRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRecordsResponse.Unmarshal(m, b)
}
func (m *PutRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRecordsResponse.Marshal(b, m, deterministic)
}
func (m *PutRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRecordsResponse.Merge(m, src)
}
func (m *PutRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_PutRecordsResponse.Size(m)
}
func (m *PutRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutRecordsResponse proto.InternalMessageInfo

type GetRecordsRequest struct {
	Shard                int64    `protobuf:"varint,1,opt,name=Shard,proto3" json:"Shard,omitempty"`
	FromOffset           uint64   `protobuf:"varint,2,opt,name=FromOffset,proto3" json:"FromOffset,omitempty"`
	Patterns             [][]byte `protobuf:"bytes,3,rep,name=Patterns,proto3" json:"Patterns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordsRequest) Reset()         { *m = GetRecordsRequest{} }
func (m *GetRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecordsRequest) ProtoMessage()    {}
func (*GetRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *GetRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordsRequest.Unmarshal(m, b)
}
func (m *GetRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordsRequest.Marshal(b, m, deterministic)
}
func (m *GetRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordsRequest.Merge(m, src)
}
func (m *GetRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecordsRequest.Size(m)
}
func (m *GetRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordsRequest proto.InternalMessageInfo

func (m *GetRecordsRequest) GetShard() int64 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *GetRecordsRequest) GetFromOffset() uint64 {
	if m != nil {
		return m.FromOffset
	}
	return 0
}

func (m *GetRecordsRequest) GetPatterns() [][]byte {
	if m != nil {
		return m.Patterns
	}
	return nil
}

type GetRecordsResponse struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=Records,proto3" json:"Records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetRecordsResponse) Reset()         { *m = GetRecordsResponse{} }
func (m *GetRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecordsResponse) ProtoMessage()    {}
func (*GetRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordsResponse.Unmarshal(m, b)
}
func (m *GetRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordsResponse.Marshal(b, m, deterministic)
}
func (m *GetRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordsResponse.Merge(m, src)
}
func (m *GetRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecordsResponse.Size(m)
}
func (m *GetRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordsResponse proto.InternalMessageInfo

func (m *GetRecordsResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type DumpRequest struct {
	DestinationURL       string   `protobuf:"bytes,1,opt,name=DestinationURL,proto3" json:"DestinationURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpRequest) Reset()         { *m = DumpRequest{} }
func (m *DumpRequest) String() string { return proto.CompactTextString(m) }
func (*DumpRequest) ProtoMessage()    {}
func (*DumpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *DumpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpRequest.Unmarshal(m, b)
}
func (m *DumpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpRequest.Marshal(b, m, deterministic)
}
func (m *DumpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpRequest.Merge(m, src)
}
func (m *DumpRequest) XXX_Size() int {
	return xxx_messageInfo_DumpRequest.Size(m)
}
func (m *DumpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DumpRequest proto.InternalMessageInfo

func (m *DumpRequest) GetDestinationURL() string {
	if m != nil {
		return m.DestinationURL
	}
	return ""
}

type DumpResponse struct {
	StartedAt            int64    `protobuf:"varint,1,opt,name=StartedAt,proto3" json:"StartedAt,omitempty"`
	ProgressBytes        int64    `protobuf:"varint,2,opt,name=ProgressBytes,proto3" json:"ProgressBytes,omitempty"`
	TotalBytes           int64    `protobuf:"varint,3,opt,name=TotalBytes,proto3" json:"TotalBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpResponse) Reset()         { *m = DumpResponse{} }
func (m *DumpResponse) String() string { return proto.CompactTextString(m) }
func (*DumpResponse) ProtoMessage()    {}
func (*DumpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *DumpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpResponse.Unmarshal(m, b)
}
func (m *DumpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpResponse.Marshal(b, m, deterministic)
}
func (m *DumpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpResponse.Merge(m, src)
}
func (m *DumpResponse) XXX_Size() int {
	return xxx_messageInfo_DumpResponse.Size(m)
}
func (m *DumpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DumpResponse proto.InternalMessageInfo

func (m *DumpResponse) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *DumpResponse) GetProgressBytes() int64 {
	if m != nil {
		return m.ProgressBytes
	}
	return 0
}

func (m *DumpResponse) GetTotalBytes() int64 {
	if m != nil {
		return m.TotalBytes
	}
	return 0
}

type SSTRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSTRequest) Reset()         { *m = SSTRequest{} }
func (m *SSTRequest) String() string { return proto.CompactTextString(m) }
func (*SSTRequest) ProtoMessage()    {}
func (*SSTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *SSTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSTRequest.Unmarshal(m, b)
}
func (m *SSTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSTRequest.Marshal(b, m, deterministic)
}
func (m *SSTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSTRequest.Merge(m, src)
}
func (m *SSTRequest) XXX_Size() int {
	return xxx_messageInfo_SSTRequest.Size(m)
}
func (m *SSTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SSTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SSTRequest proto.InternalMessageInfo

type SSTResponseChunk struct {
	Chunk                []byte   `protobuf:"bytes,1,opt,name=Chunk,proto3" json:"Chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSTResponseChunk) Reset()         { *m = SSTResponseChunk{} }
func (m *SSTResponseChunk) String() string { return proto.CompactTextString(m) }
func (*SSTResponseChunk) ProtoMessage()    {}
func (*SSTResponseChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *SSTResponseChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSTResponseChunk.Unmarshal(m, b)
}
func (m *SSTResponseChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSTResponseChunk.Marshal(b, m, deterministic)
}
func (m *SSTResponseChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSTResponseChunk.Merge(m, src)
}
func (m *SSTResponseChunk) XXX_Size() int {
	return xxx_messageInfo_SSTResponseChunk.Size(m)
}
func (m *SSTResponseChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_SSTResponseChunk.DiscardUnknown(m)
}

var xxx_messageInfo_SSTResponseChunk proto.InternalMessageInfo

func (m *SSTResponseChunk) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

type LoadRequest struct {
	SourceURL            string   `protobuf:"bytes,1,opt,name=SourceURL,proto3" json:"SourceURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadRequest) Reset()         { *m = LoadRequest{} }
func (m *LoadRequest) String() string { return proto.CompactTextString(m) }
func (*LoadRequest) ProtoMessage()    {}
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *LoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRequest.Unmarshal(m, b)
}
func (m *LoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRequest.Marshal(b, m, deterministic)
}
func (m *LoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRequest.Merge(m, src)
}
func (m *LoadRequest) XXX_Size() int {
	return xxx_messageInfo_LoadRequest.Size(m)
}
func (m *LoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRequest proto.InternalMessageInfo

func (m *LoadRequest) GetSourceURL() string {
	if m != nil {
		return m.SourceURL
	}
	return ""
}

type LoadResponse struct {
	StartedAt            int64    `protobuf:"varint,1,opt,name=StartedAt,proto3" json:"StartedAt,omitempty"`
	ProgressBytes        int64    `protobuf:"varint,2,opt,name=ProgressBytes,proto3" json:"ProgressBytes,omitempty"`
	TotalBytes           int64    `protobuf:"varint,3,opt,name=TotalBytes,proto3" json:"TotalBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadResponse) Reset()         { *m = LoadResponse{} }
func (m *LoadResponse) String() string { return proto.CompactTextString(m) }
func (*LoadResponse) ProtoMessage()    {}
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *LoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadResponse.Unmarshal(m, b)
}
func (m *LoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadResponse.Marshal(b, m, deterministic)
}
func (m *LoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadResponse.Merge(m, src)
}
func (m *LoadResponse) XXX_Size() int {
	return xxx_messageInfo_LoadResponse.Size(m)
}
func (m *LoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadResponse proto.InternalMessageInfo

func (m *LoadResponse) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *LoadResponse) GetProgressBytes() int64 {
	if m != nil {
		return m.ProgressBytes
	}
	return 0
}

func (m *LoadResponse) GetTotalBytes() int64 {
	if m != nil {
		return m.TotalBytes
	}
	return 0
}

func init() {
	proto.RegisterType((*Record)(nil), "api.Record")
	proto.RegisterType((*PutRecordsRequest)(nil), "api.PutRecordsRequest")
	proto.RegisterType((*PutRecordsResponse)(nil), "api.PutRecordsResponse")
	proto.RegisterType((*GetRecordsRequest)(nil), "api.GetRecordsRequest")
	proto.RegisterType((*GetRecordsResponse)(nil), "api.GetRecordsResponse")
	proto.RegisterType((*DumpRequest)(nil), "api.DumpRequest")
	proto.RegisterType((*DumpResponse)(nil), "api.DumpResponse")
	proto.RegisterType((*SSTRequest)(nil), "api.SSTRequest")
	proto.RegisterType((*SSTResponseChunk)(nil), "api.SSTResponseChunk")
	proto.RegisterType((*LoadRequest)(nil), "api.LoadRequest")
	proto.RegisterType((*LoadResponse)(nil), "api.LoadResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0x37, 0x98, 0xfd, 0x93, 0x49, 0x40, 0xac, 0x55, 0x41, 0xb4, 0x5a, 0xa1, 0xc8, 0x02,
	0x14, 0x09, 0x69, 0x85, 0x16, 0x71, 0x81, 0x03, 0x5a, 0x58, 0xc1, 0x65, 0x11, 0x91, 0x13, 0xb8,
	0x9b, 0x66, 0xda, 0x46, 0x34, 0x71, 0xb0, 0x9d, 0x43, 0xbf, 0x04, 0x9f, 0x19, 0xc5, 0x4e, 0x9a,
	0xd0, 0x5c, 0x38, 0x71, 0xeb, 0xfb, 0x75, 0x3c, 0xf3, 0xc6, 0x7e, 0x01, 0x5f, 0x34, 0xe5, 0x55,
	0xa3, 0xa4, 0x91, 0x94, 0x88, 0xa6, 0x64, 0xdf, 0xe1, 0x84, 0xe3, 0x52, 0xaa, 0x82, 0x5e, 0x82,
	0x9f, 0x97, 0x15, 0x6a, 0x23, 0xaa, 0x26, 0xf2, 0x62, 0x2f, 0x21, 0x7c, 0x04, 0x74, 0x01, 0xc7,
	0xb9, 0x6c, 0xca, 0x65, 0x74, 0x2f, 0xf6, 0x92, 0x90, 0x3b, 0x41, 0x23, 0x38, 0x4d, 0xc5, 0x6e,
	0x2b, 0x45, 0x11, 0x11, 0xcb, 0x07, 0xc9, 0xde, 0xc2, 0x79, 0xda, 0x1a, 0xd7, 0x5a, 0x73, 0xfc,
	0xd5, 0xa2, 0x36, 0xf4, 0x39, 0x9c, 0xf6, 0x24, 0xf2, 0x62, 0x92, 0x04, 0xd7, 0xc1, 0x55, 0x67,
	0xc7, 0x31, 0x3e, 0xfc, 0xc7, 0x16, 0x40, 0xa7, 0x67, 0x75, 0x23, 0x6b, 0x8d, 0x0c, 0xe1, 0xfc,
	0x33, 0x1e, 0x76, 0x5c, 0xc0, 0x71, 0xb6, 0x11, 0xaa, 0xe8, 0x0d, 0x3b, 0x41, 0x9f, 0x02, 0x7c,
	0x52, 0xb2, 0xfa, 0xba, 0x5a, 0x69, 0x34, 0xd6, 0xf1, 0x7d, 0x3e, 0x21, 0xf4, 0x02, 0xce, 0x52,
	0x61, 0x0c, 0xaa, 0x5a, 0x47, 0x24, 0x26, 0x49, 0xc8, 0xf7, 0x9a, 0xbd, 0x03, 0x3a, 0x1d, 0xe3,
	0x86, 0xff, 0xab, 0xf3, 0x37, 0x10, 0xdc, 0xb6, 0x55, 0x33, 0xb8, 0x7b, 0x01, 0x0f, 0x6f, 0x51,
	0x9b, 0xb2, 0x16, 0xa6, 0x94, 0xf5, 0x37, 0x7e, 0x67, 0x6d, 0xfa, 0xfc, 0x80, 0x32, 0x05, 0xa1,
	0x3b, 0xd6, 0x4f, 0xbb, 0x04, 0x3f, 0x33, 0x42, 0x19, 0x2c, 0x6e, 0xcc, 0xf0, 0x14, 0x7b, 0x40,
	0x9f, 0xc1, 0x83, 0x54, 0xc9, 0xb5, 0x42, 0xad, 0x3f, 0xec, 0x0c, 0x6a, 0xbb, 0x20, 0xe1, 0x7f,
	0xc3, 0xee, 0x0e, 0x72, 0x69, 0xc4, 0xd6, 0x95, 0x10, 0x5b, 0x32, 0x21, 0x2c, 0x04, 0xc8, 0xb2,
	0xbc, 0x77, 0xca, 0x12, 0x78, 0x64, 0x95, 0x33, 0xf0, 0x71, 0xd3, 0xd6, 0x3f, 0xbb, 0xbb, 0xb5,
	0x3f, 0xac, 0x83, 0x90, 0x3b, 0xc1, 0x5e, 0x42, 0x70, 0x27, 0x45, 0x31, 0xac, 0xd8, 0x59, 0x95,
	0xad, 0x5a, 0xe2, 0xb8, 0xdd, 0x08, 0xba, 0xc5, 0x5c, 0xf1, 0xff, 0x5b, 0xec, 0xfa, 0xb7, 0x07,
	0x67, 0x5f, 0x50, 0x6b, 0xb1, 0x46, 0x4d, 0xdf, 0x03, 0x8c, 0x51, 0xa2, 0x8f, 0xed, 0xa3, 0xcd,
	0x72, 0x79, 0xf1, 0x64, 0xc6, 0xfb, 0xcc, 0x1d, 0xd1, 0x1b, 0x80, 0x31, 0x0e, 0x7d, 0x83, 0x59,
	0x0c, 0xfb, 0x06, 0xf3, 0xdc, 0xb0, 0xa3, 0x57, 0xde, 0x8f, 0x13, 0xfb, 0xb9, 0xbd, 0xfe, 0x13,
	0x00, 0x00, 0xff, 0xff, 0xec, 0xd2, 0x69, 0xca, 0x7b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessagesClient is the client API for Messages service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessagesClient interface {
	PutRecords(ctx context.Context, in *PutRecordsRequest, opts ...grpc.CallOption) (*PutRecordsResponse, error)
	GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (Messages_GetRecordsClient, error)
}

type messagesClient struct {
	cc *grpc.ClientConn
}

func NewMessagesClient(cc *grpc.ClientConn) MessagesClient {
	return &messagesClient{cc}
}

func (c *messagesClient) PutRecords(ctx context.Context, in *PutRecordsRequest, opts ...grpc.CallOption) (*PutRecordsResponse, error) {
	out := new(PutRecordsResponse)
	err := c.cc.Invoke(ctx, "/api.Messages/PutRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesClient) GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (Messages_GetRecordsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Messages_serviceDesc.Streams[0], "/api.Messages/GetRecords", opts...)
	if err != nil {
		return nil, err
	}
	x := &messagesGetRecordsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Messages_GetRecordsClient interface {
	Recv() (*GetRecordsResponse, error)
	grpc.ClientStream
}

type messagesGetRecordsClient struct {
	grpc.ClientStream
}

func (x *messagesGetRecordsClient) Recv() (*GetRecordsResponse, error) {
	m := new(GetRecordsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessagesServer is the server API for Messages service.
type MessagesServer interface {
	PutRecords(context.Context, *PutRecordsRequest) (*PutRecordsResponse, error)
	GetRecords(*GetRecordsRequest, Messages_GetRecordsServer) error
}

// UnimplementedMessagesServer can be embedded to have forward compatible implementations.
type UnimplementedMessagesServer struct {
}

func (*UnimplementedMessagesServer) PutRecords(ctx context.Context, req *PutRecordsRequest) (*PutRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutRecords not implemented")
}
func (*UnimplementedMessagesServer) GetRecords(req *GetRecordsRequest, srv Messages_GetRecordsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRecords not implemented")
}

func RegisterMessagesServer(s *grpc.Server, srv MessagesServer) {
	s.RegisterService(&_Messages_serviceDesc, srv)
}

func _Messages_PutRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServer).PutRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Messages/PutRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServer).PutRecords(ctx, req.(*PutRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messages_GetRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRecordsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessagesServer).GetRecords(m, &messagesGetRecordsServer{stream})
}

type Messages_GetRecordsServer interface {
	Send(*GetRecordsResponse) error
	grpc.ServerStream
}

type messagesGetRecordsServer struct {
	grpc.ServerStream
}

func (x *messagesGetRecordsServer) Send(m *GetRecordsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Messages_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Messages",
	HandlerType: (*MessagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutRecords",
			Handler:    _Messages_PutRecords_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRecords",
			Handler:       _Messages_GetRecords_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
