// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nest.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Topic                []byte   `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Retained             bool     `protobuf:"varint,4,opt,name=Retained,proto3" json:"Retained,omitempty"`
	Sender               string   `protobuf:"bytes,5,opt,name=Sender,proto3" json:"Sender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Record) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Record) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Record) GetRetained() bool {
	if m != nil {
		return m.Retained
	}
	return false
}

func (m *Record) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

type PutRecordsRequest struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=Records,proto3" json:"Records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PutRecordsRequest) Reset()         { *m = PutRecordsRequest{} }
func (m *PutRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*PutRecordsRequest) ProtoMessage()    {}
func (*PutRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{1}
}

func (m *PutRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRecordsRequest.Unmarshal(m, b)
}
func (m *PutRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRecordsRequest.Marshal(b, m, deterministic)
}
func (m *PutRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRecordsRequest.Merge(m, src)
}
func (m *PutRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_PutRecordsRequest.Size(m)
}
func (m *PutRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRecordsRequest proto.InternalMessageInfo

func (m *PutRecordsRequest) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type PutRecordsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRecordsResponse) Reset()         { *m = PutRecordsResponse{} }
func (m *PutRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*PutRecordsResponse) ProtoMessage()    {}
func (*PutRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{2}
}

func (m *PutRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRecordsResponse.Unmarshal(m, b)
}
func (m *PutRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRecordsResponse.Marshal(b, m, deterministic)
}
func (m *PutRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRecordsResponse.Merge(m, src)
}
func (m *PutRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_PutRecordsResponse.Size(m)
}
func (m *PutRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutRecordsResponse proto.InternalMessageInfo

type GetRecordsRequest struct {
	FromOffset           int64    `protobuf:"varint,1,opt,name=FromOffset,proto3" json:"FromOffset,omitempty"`
	FromTimestamp        int64    `protobuf:"varint,2,opt,name=FromTimestamp,proto3" json:"FromTimestamp,omitempty"`
	Patterns             [][]byte `protobuf:"bytes,3,rep,name=Patterns,proto3" json:"Patterns,omitempty"`
	Watch                bool     `protobuf:"varint,4,opt,name=Watch,proto3" json:"Watch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordsRequest) Reset()         { *m = GetRecordsRequest{} }
func (m *GetRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecordsRequest) ProtoMessage()    {}
func (*GetRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{3}
}

func (m *GetRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordsRequest.Unmarshal(m, b)
}
func (m *GetRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordsRequest.Marshal(b, m, deterministic)
}
func (m *GetRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordsRequest.Merge(m, src)
}
func (m *GetRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecordsRequest.Size(m)
}
func (m *GetRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordsRequest proto.InternalMessageInfo

func (m *GetRecordsRequest) GetFromOffset() int64 {
	if m != nil {
		return m.FromOffset
	}
	return 0
}

func (m *GetRecordsRequest) GetFromTimestamp() int64 {
	if m != nil {
		return m.FromTimestamp
	}
	return 0
}

func (m *GetRecordsRequest) GetPatterns() [][]byte {
	if m != nil {
		return m.Patterns
	}
	return nil
}

func (m *GetRecordsRequest) GetWatch() bool {
	if m != nil {
		return m.Watch
	}
	return false
}

type GetRecordsResponse struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=Records,proto3" json:"Records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetRecordsResponse) Reset()         { *m = GetRecordsResponse{} }
func (m *GetRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecordsResponse) ProtoMessage()    {}
func (*GetRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{4}
}

func (m *GetRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordsResponse.Unmarshal(m, b)
}
func (m *GetRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordsResponse.Marshal(b, m, deterministic)
}
func (m *GetRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordsResponse.Merge(m, src)
}
func (m *GetRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecordsResponse.Size(m)
}
func (m *GetRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordsResponse proto.InternalMessageInfo

func (m *GetRecordsResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type LoadResponse struct {
	StartedAt            int64    `protobuf:"varint,1,opt,name=StartedAt,proto3" json:"StartedAt,omitempty"`
	ProgressBytes        int64    `protobuf:"varint,2,opt,name=ProgressBytes,proto3" json:"ProgressBytes,omitempty"`
	TotalBytes           int64    `protobuf:"varint,3,opt,name=TotalBytes,proto3" json:"TotalBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadResponse) Reset()         { *m = LoadResponse{} }
func (m *LoadResponse) String() string { return proto.CompactTextString(m) }
func (*LoadResponse) ProtoMessage()    {}
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{5}
}

func (m *LoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadResponse.Unmarshal(m, b)
}
func (m *LoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadResponse.Marshal(b, m, deterministic)
}
func (m *LoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadResponse.Merge(m, src)
}
func (m *LoadResponse) XXX_Size() int {
	return xxx_messageInfo_LoadResponse.Size(m)
}
func (m *LoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadResponse proto.InternalMessageInfo

func (m *LoadResponse) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *LoadResponse) GetProgressBytes() int64 {
	if m != nil {
		return m.ProgressBytes
	}
	return 0
}

func (m *LoadResponse) GetTotalBytes() int64 {
	if m != nil {
		return m.TotalBytes
	}
	return 0
}

type TopicMetadata struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	MessageCount         uint64   `protobuf:"varint,2,opt,name=MessageCount,proto3" json:"MessageCount,omitempty"`
	LastRecord           *Record  `protobuf:"bytes,3,opt,name=LastRecord,proto3" json:"LastRecord,omitempty"`
	SizeInBytes          uint64   `protobuf:"varint,4,opt,name=SizeInBytes,proto3" json:"SizeInBytes,omitempty"`
	GuessedContentType   string   `protobuf:"bytes,5,opt,name=GuessedContentType,proto3" json:"GuessedContentType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicMetadata) Reset()         { *m = TopicMetadata{} }
func (m *TopicMetadata) String() string { return proto.CompactTextString(m) }
func (*TopicMetadata) ProtoMessage()    {}
func (*TopicMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{6}
}

func (m *TopicMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicMetadata.Unmarshal(m, b)
}
func (m *TopicMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicMetadata.Marshal(b, m, deterministic)
}
func (m *TopicMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicMetadata.Merge(m, src)
}
func (m *TopicMetadata) XXX_Size() int {
	return xxx_messageInfo_TopicMetadata.Size(m)
}
func (m *TopicMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TopicMetadata proto.InternalMessageInfo

func (m *TopicMetadata) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *TopicMetadata) GetMessageCount() uint64 {
	if m != nil {
		return m.MessageCount
	}
	return 0
}

func (m *TopicMetadata) GetLastRecord() *Record {
	if m != nil {
		return m.LastRecord
	}
	return nil
}

func (m *TopicMetadata) GetSizeInBytes() uint64 {
	if m != nil {
		return m.SizeInBytes
	}
	return 0
}

func (m *TopicMetadata) GetGuessedContentType() string {
	if m != nil {
		return m.GuessedContentType
	}
	return ""
}

type ListTopicsRequest struct {
	Pattern              []byte   `protobuf:"bytes,1,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTopicsRequest) Reset()         { *m = ListTopicsRequest{} }
func (m *ListTopicsRequest) String() string { return proto.CompactTextString(m) }
func (*ListTopicsRequest) ProtoMessage()    {}
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{7}
}

func (m *ListTopicsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTopicsRequest.Unmarshal(m, b)
}
func (m *ListTopicsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTopicsRequest.Marshal(b, m, deterministic)
}
func (m *ListTopicsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTopicsRequest.Merge(m, src)
}
func (m *ListTopicsRequest) XXX_Size() int {
	return xxx_messageInfo_ListTopicsRequest.Size(m)
}
func (m *ListTopicsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTopicsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTopicsRequest proto.InternalMessageInfo

func (m *ListTopicsRequest) GetPattern() []byte {
	if m != nil {
		return m.Pattern
	}
	return nil
}

type ListTopicsResponse struct {
	TopicMetadatas       []*TopicMetadata `protobuf:"bytes,1,rep,name=TopicMetadatas,proto3" json:"TopicMetadatas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListTopicsResponse) Reset()         { *m = ListTopicsResponse{} }
func (m *ListTopicsResponse) String() string { return proto.CompactTextString(m) }
func (*ListTopicsResponse) ProtoMessage()    {}
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{8}
}

func (m *ListTopicsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTopicsResponse.Unmarshal(m, b)
}
func (m *ListTopicsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTopicsResponse.Marshal(b, m, deterministic)
}
func (m *ListTopicsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTopicsResponse.Merge(m, src)
}
func (m *ListTopicsResponse) XXX_Size() int {
	return xxx_messageInfo_ListTopicsResponse.Size(m)
}
func (m *ListTopicsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTopicsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTopicsResponse proto.InternalMessageInfo

func (m *ListTopicsResponse) GetTopicMetadatas() []*TopicMetadata {
	if m != nil {
		return m.TopicMetadatas
	}
	return nil
}

type GetTopicsRequest struct {
	Pattern              []byte   `protobuf:"bytes,1,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopicsRequest) Reset()         { *m = GetTopicsRequest{} }
func (m *GetTopicsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopicsRequest) ProtoMessage()    {}
func (*GetTopicsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{9}
}

func (m *GetTopicsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicsRequest.Unmarshal(m, b)
}
func (m *GetTopicsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicsRequest.Marshal(b, m, deterministic)
}
func (m *GetTopicsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicsRequest.Merge(m, src)
}
func (m *GetTopicsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopicsRequest.Size(m)
}
func (m *GetTopicsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicsRequest proto.InternalMessageInfo

func (m *GetTopicsRequest) GetPattern() []byte {
	if m != nil {
		return m.Pattern
	}
	return nil
}

type GetTopicsResponse struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=Records,proto3" json:"Records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetTopicsResponse) Reset()         { *m = GetTopicsResponse{} }
func (m *GetTopicsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTopicsResponse) ProtoMessage()    {}
func (*GetTopicsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{10}
}

func (m *GetTopicsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicsResponse.Unmarshal(m, b)
}
func (m *GetTopicsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicsResponse.Marshal(b, m, deterministic)
}
func (m *GetTopicsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicsResponse.Merge(m, src)
}
func (m *GetTopicsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTopicsResponse.Size(m)
}
func (m *GetTopicsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicsResponse proto.InternalMessageInfo

func (m *GetTopicsResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type SSTRequest struct {
	Stream               string   `protobuf:"bytes,1,opt,name=Stream,proto3" json:"Stream,omitempty"`
	Shard                uint64   `protobuf:"varint,2,opt,name=Shard,proto3" json:"Shard,omitempty"`
	ToOffset             uint64   `protobuf:"varint,3,opt,name=ToOffset,proto3" json:"ToOffset,omitempty"`
	FromOffset           uint64   `protobuf:"varint,4,opt,name=FromOffset,proto3" json:"FromOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSTRequest) Reset()         { *m = SSTRequest{} }
func (m *SSTRequest) String() string { return proto.CompactTextString(m) }
func (*SSTRequest) ProtoMessage()    {}
func (*SSTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{11}
}

func (m *SSTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSTRequest.Unmarshal(m, b)
}
func (m *SSTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSTRequest.Marshal(b, m, deterministic)
}
func (m *SSTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSTRequest.Merge(m, src)
}
func (m *SSTRequest) XXX_Size() int {
	return xxx_messageInfo_SSTRequest.Size(m)
}
func (m *SSTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SSTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SSTRequest proto.InternalMessageInfo

func (m *SSTRequest) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *SSTRequest) GetShard() uint64 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *SSTRequest) GetToOffset() uint64 {
	if m != nil {
		return m.ToOffset
	}
	return 0
}

func (m *SSTRequest) GetFromOffset() uint64 {
	if m != nil {
		return m.FromOffset
	}
	return 0
}

type SSTResponseChunk struct {
	Chunk                []byte   `protobuf:"bytes,1,opt,name=Chunk,proto3" json:"Chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSTResponseChunk) Reset()         { *m = SSTResponseChunk{} }
func (m *SSTResponseChunk) String() string { return proto.CompactTextString(m) }
func (*SSTResponseChunk) ProtoMessage()    {}
func (*SSTResponseChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{12}
}

func (m *SSTResponseChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSTResponseChunk.Unmarshal(m, b)
}
func (m *SSTResponseChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSTResponseChunk.Marshal(b, m, deterministic)
}
func (m *SSTResponseChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSTResponseChunk.Merge(m, src)
}
func (m *SSTResponseChunk) XXX_Size() int {
	return xxx_messageInfo_SSTResponseChunk.Size(m)
}
func (m *SSTResponseChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_SSTResponseChunk.DiscardUnknown(m)
}

var xxx_messageInfo_SSTResponseChunk proto.InternalMessageInfo

func (m *SSTResponseChunk) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

type LoadRequest struct {
	Stream               string   `protobuf:"bytes,1,opt,name=Stream,proto3" json:"Stream,omitempty"`
	Shard                uint64   `protobuf:"varint,2,opt,name=Shard,proto3" json:"Shard,omitempty"`
	SourceURL            string   `protobuf:"bytes,3,opt,name=SourceURL,proto3" json:"SourceURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadRequest) Reset()         { *m = LoadRequest{} }
func (m *LoadRequest) String() string { return proto.CompactTextString(m) }
func (*LoadRequest) ProtoMessage()    {}
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{13}
}

func (m *LoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRequest.Unmarshal(m, b)
}
func (m *LoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRequest.Marshal(b, m, deterministic)
}
func (m *LoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRequest.Merge(m, src)
}
func (m *LoadRequest) XXX_Size() int {
	return xxx_messageInfo_LoadRequest.Size(m)
}
func (m *LoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRequest proto.InternalMessageInfo

func (m *LoadRequest) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *LoadRequest) GetShard() uint64 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *LoadRequest) GetSourceURL() string {
	if m != nil {
		return m.SourceURL
	}
	return ""
}

type DumpRequest struct {
	Stream               string   `protobuf:"bytes,1,opt,name=Stream,proto3" json:"Stream,omitempty"`
	Shard                uint64   `protobuf:"varint,2,opt,name=Shard,proto3" json:"Shard,omitempty"`
	DestinationURL       string   `protobuf:"bytes,3,opt,name=DestinationURL,proto3" json:"DestinationURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpRequest) Reset()         { *m = DumpRequest{} }
func (m *DumpRequest) String() string { return proto.CompactTextString(m) }
func (*DumpRequest) ProtoMessage()    {}
func (*DumpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{14}
}

func (m *DumpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpRequest.Unmarshal(m, b)
}
func (m *DumpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpRequest.Marshal(b, m, deterministic)
}
func (m *DumpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpRequest.Merge(m, src)
}
func (m *DumpRequest) XXX_Size() int {
	return xxx_messageInfo_DumpRequest.Size(m)
}
func (m *DumpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DumpRequest proto.InternalMessageInfo

func (m *DumpRequest) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *DumpRequest) GetShard() uint64 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *DumpRequest) GetDestinationURL() string {
	if m != nil {
		return m.DestinationURL
	}
	return ""
}

type DumpResponse struct {
	StartedAt            int64    `protobuf:"varint,1,opt,name=StartedAt,proto3" json:"StartedAt,omitempty"`
	ProgressBytes        int64    `protobuf:"varint,2,opt,name=ProgressBytes,proto3" json:"ProgressBytes,omitempty"`
	TotalBytes           int64    `protobuf:"varint,3,opt,name=TotalBytes,proto3" json:"TotalBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpResponse) Reset()         { *m = DumpResponse{} }
func (m *DumpResponse) String() string { return proto.CompactTextString(m) }
func (*DumpResponse) ProtoMessage()    {}
func (*DumpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{15}
}

func (m *DumpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpResponse.Unmarshal(m, b)
}
func (m *DumpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpResponse.Marshal(b, m, deterministic)
}
func (m *DumpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpResponse.Merge(m, src)
}
func (m *DumpResponse) XXX_Size() int {
	return xxx_messageInfo_DumpResponse.Size(m)
}
func (m *DumpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DumpResponse proto.InternalMessageInfo

func (m *DumpResponse) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *DumpResponse) GetProgressBytes() int64 {
	if m != nil {
		return m.ProgressBytes
	}
	return 0
}

func (m *DumpResponse) GetTotalBytes() int64 {
	if m != nil {
		return m.TotalBytes
	}
	return 0
}

type EventAttribute struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventAttribute) Reset()         { *m = EventAttribute{} }
func (m *EventAttribute) String() string { return proto.CompactTextString(m) }
func (*EventAttribute) ProtoMessage()    {}
func (*EventAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{16}
}

func (m *EventAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventAttribute.Unmarshal(m, b)
}
func (m *EventAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventAttribute.Marshal(b, m, deterministic)
}
func (m *EventAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAttribute.Merge(m, src)
}
func (m *EventAttribute) XXX_Size() int {
	return xxx_messageInfo_EventAttribute.Size(m)
}
func (m *EventAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_EventAttribute proto.InternalMessageInfo

func (m *EventAttribute) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EventAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Event struct {
	Timestamp            int64             `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Tenant               string            `protobuf:"bytes,2,opt,name=Tenant,proto3" json:"Tenant,omitempty"`
	Service              string            `protobuf:"bytes,3,opt,name=Service,proto3" json:"Service,omitempty"`
	Kind                 string            `protobuf:"bytes,4,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Attributes           []*EventAttribute `protobuf:"bytes,5,rep,name=Attributes,proto3" json:"Attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{17}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *Event) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Event) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Event) GetAttributes() []*EventAttribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type PutEventRequest struct {
	Timestamp            int64             `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Tenant               string            `protobuf:"bytes,2,opt,name=Tenant,proto3" json:"Tenant,omitempty"`
	Service              string            `protobuf:"bytes,3,opt,name=Service,proto3" json:"Service,omitempty"`
	Kind                 string            `protobuf:"bytes,4,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Attributes           []*EventAttribute `protobuf:"bytes,5,rep,name=Attributes,proto3" json:"Attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PutEventRequest) Reset()         { *m = PutEventRequest{} }
func (m *PutEventRequest) String() string { return proto.CompactTextString(m) }
func (*PutEventRequest) ProtoMessage()    {}
func (*PutEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{18}
}

func (m *PutEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutEventRequest.Unmarshal(m, b)
}
func (m *PutEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutEventRequest.Marshal(b, m, deterministic)
}
func (m *PutEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutEventRequest.Merge(m, src)
}
func (m *PutEventRequest) XXX_Size() int {
	return xxx_messageInfo_PutEventRequest.Size(m)
}
func (m *PutEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutEventRequest proto.InternalMessageInfo

func (m *PutEventRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PutEventRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *PutEventRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *PutEventRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *PutEventRequest) GetAttributes() []*EventAttribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type PutEventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutEventResponse) Reset()         { *m = PutEventResponse{} }
func (m *PutEventResponse) String() string { return proto.CompactTextString(m) }
func (*PutEventResponse) ProtoMessage()    {}
func (*PutEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{19}
}

func (m *PutEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutEventResponse.Unmarshal(m, b)
}
func (m *PutEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutEventResponse.Marshal(b, m, deterministic)
}
func (m *PutEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutEventResponse.Merge(m, src)
}
func (m *PutEventResponse) XXX_Size() int {
	return xxx_messageInfo_PutEventResponse.Size(m)
}
func (m *PutEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutEventResponse proto.InternalMessageInfo

type GetEventRequest struct {
	Tenant               string   `protobuf:"bytes,1,opt,name=Tenant,proto3" json:"Tenant,omitempty"`
	FromOffset           int64    `protobuf:"varint,2,opt,name=FromOffset,proto3" json:"FromOffset,omitempty"`
	FromTimestamp        int64    `protobuf:"varint,3,opt,name=FromTimestamp,proto3" json:"FromTimestamp,omitempty"`
	Watch                bool     `protobuf:"varint,4,opt,name=Watch,proto3" json:"Watch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventRequest) Reset()         { *m = GetEventRequest{} }
func (m *GetEventRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventRequest) ProtoMessage()    {}
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{20}
}

func (m *GetEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventRequest.Unmarshal(m, b)
}
func (m *GetEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventRequest.Marshal(b, m, deterministic)
}
func (m *GetEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventRequest.Merge(m, src)
}
func (m *GetEventRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventRequest.Size(m)
}
func (m *GetEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventRequest proto.InternalMessageInfo

func (m *GetEventRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *GetEventRequest) GetFromOffset() int64 {
	if m != nil {
		return m.FromOffset
	}
	return 0
}

func (m *GetEventRequest) GetFromTimestamp() int64 {
	if m != nil {
		return m.FromTimestamp
	}
	return 0
}

func (m *GetEventRequest) GetWatch() bool {
	if m != nil {
		return m.Watch
	}
	return false
}

type GetEventResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=Events,proto3" json:"Events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventResponse) Reset()         { *m = GetEventResponse{} }
func (m *GetEventResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventResponse) ProtoMessage()    {}
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90c05566c01c366f, []int{21}
}

func (m *GetEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventResponse.Unmarshal(m, b)
}
func (m *GetEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventResponse.Marshal(b, m, deterministic)
}
func (m *GetEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventResponse.Merge(m, src)
}
func (m *GetEventResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventResponse.Size(m)
}
func (m *GetEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventResponse proto.InternalMessageInfo

func (m *GetEventResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "api.Record")
	proto.RegisterType((*PutRecordsRequest)(nil), "api.PutRecordsRequest")
	proto.RegisterType((*PutRecordsResponse)(nil), "api.PutRecordsResponse")
	proto.RegisterType((*GetRecordsRequest)(nil), "api.GetRecordsRequest")
	proto.RegisterType((*GetRecordsResponse)(nil), "api.GetRecordsResponse")
	proto.RegisterType((*LoadResponse)(nil), "api.LoadResponse")
	proto.RegisterType((*TopicMetadata)(nil), "api.TopicMetadata")
	proto.RegisterType((*ListTopicsRequest)(nil), "api.ListTopicsRequest")
	proto.RegisterType((*ListTopicsResponse)(nil), "api.ListTopicsResponse")
	proto.RegisterType((*GetTopicsRequest)(nil), "api.GetTopicsRequest")
	proto.RegisterType((*GetTopicsResponse)(nil), "api.GetTopicsResponse")
	proto.RegisterType((*SSTRequest)(nil), "api.SSTRequest")
	proto.RegisterType((*SSTResponseChunk)(nil), "api.SSTResponseChunk")
	proto.RegisterType((*LoadRequest)(nil), "api.LoadRequest")
	proto.RegisterType((*DumpRequest)(nil), "api.DumpRequest")
	proto.RegisterType((*DumpResponse)(nil), "api.DumpResponse")
	proto.RegisterType((*EventAttribute)(nil), "api.EventAttribute")
	proto.RegisterType((*Event)(nil), "api.Event")
	proto.RegisterType((*PutEventRequest)(nil), "api.PutEventRequest")
	proto.RegisterType((*PutEventResponse)(nil), "api.PutEventResponse")
	proto.RegisterType((*GetEventRequest)(nil), "api.GetEventRequest")
	proto.RegisterType((*GetEventResponse)(nil), "api.GetEventResponse")
}

func init() { proto.RegisterFile("nest.proto", fileDescriptor_90c05566c01c366f) }

var fileDescriptor_90c05566c01c366f = []byte{
	// 924 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x51, 0x6f, 0xe3, 0x44,
	0x10, 0xae, 0xeb, 0x34, 0x6d, 0x26, 0xb9, 0x36, 0x1d, 0x7a, 0x25, 0xaa, 0x4e, 0x28, 0x5a, 0x01,
	0x8a, 0x04, 0xf4, 0xa0, 0x27, 0x21, 0x28, 0x08, 0x54, 0x7a, 0x50, 0xa1, 0xeb, 0x41, 0xb4, 0x0e,
	0x20, 0x1e, 0xf7, 0xe2, 0xb9, 0xab, 0x45, 0x63, 0x07, 0xef, 0xba, 0x52, 0x79, 0xe3, 0x81, 0x17,
	0x78, 0xe0, 0x1f, 0x20, 0x9e, 0xf9, 0x21, 0xfc, 0x2e, 0xb4, 0xb3, 0xeb, 0xd8, 0x4e, 0x2a, 0x5d,
	0xd5, 0x07, 0x74, 0x6f, 0x9e, 0x6f, 0x77, 0x67, 0xbe, 0x99, 0x9d, 0xfd, 0xc6, 0x00, 0x29, 0x69,
	0x73, 0x38, 0xcf, 0x33, 0x93, 0x61, 0xa8, 0xe6, 0x89, 0xf8, 0x3d, 0x80, 0xb6, 0xa4, 0x69, 0x96,
	0xc7, 0xf8, 0x00, 0x3a, 0x93, 0x64, 0x46, 0xda, 0xa8, 0xd9, 0x7c, 0x10, 0x0c, 0x83, 0x51, 0x28,
	0x2b, 0x00, 0xf7, 0x60, 0x63, 0x92, 0xcd, 0x93, 0xe9, 0x60, 0x7d, 0x18, 0x8c, 0x7a, 0xd2, 0x19,
	0x38, 0x80, 0xcd, 0xb1, 0xba, 0xbe, 0xcc, 0x54, 0x3c, 0x08, 0x19, 0x2f, 0x4d, 0x3c, 0x80, 0x2d,
	0x49, 0x46, 0x25, 0x29, 0xc5, 0x83, 0xd6, 0x30, 0x18, 0x6d, 0xc9, 0x85, 0x8d, 0xfb, 0xd0, 0x8e,
	0x28, 0x8d, 0x29, 0x1f, 0x6c, 0x0c, 0x83, 0x51, 0x47, 0x7a, 0x4b, 0x1c, 0xc3, 0xee, 0xb8, 0x30,
	0x8e, 0x8e, 0x96, 0xf4, 0x73, 0x41, 0xda, 0xe0, 0x5b, 0xb0, 0xe9, 0x91, 0x41, 0x30, 0x0c, 0x47,
	0xdd, 0xa3, 0xee, 0xa1, 0x9a, 0x27, 0x87, 0x0e, 0x93, 0xe5, 0x9a, 0xd8, 0x03, 0xac, 0x9f, 0xd5,
	0xf3, 0x2c, 0xd5, 0x24, 0xfe, 0x08, 0x60, 0xf7, 0x8c, 0x96, 0x5d, 0xbe, 0x01, 0xf0, 0x55, 0x9e,
	0xcd, 0xbe, 0x7d, 0xfe, 0x5c, 0x93, 0xf1, 0xa9, 0xd6, 0x10, 0x7c, 0x13, 0xee, 0x59, 0xab, 0xaa,
	0xc6, 0x3a, 0x6f, 0x69, 0x82, 0x36, 0xc3, 0xb1, 0x32, 0x86, 0xf2, 0x54, 0x0f, 0xc2, 0x61, 0x38,
	0xea, 0xc9, 0x85, 0x6d, 0xab, 0xf5, 0x83, 0x32, 0xd3, 0x0b, 0x9f, 0xba, 0x33, 0xc4, 0x27, 0x80,
	0x75, 0x32, 0x8e, 0xe3, 0x6d, 0x13, 0xcc, 0xa1, 0x77, 0x9e, 0xa9, 0x78, 0x71, 0xec, 0x01, 0x74,
	0x22, 0xa3, 0x72, 0x43, 0xf1, 0x49, 0x99, 0x43, 0x05, 0xd8, 0x14, 0xc6, 0x79, 0xf6, 0x22, 0x27,
	0xad, 0xbf, 0xb8, 0x36, 0xa4, 0xcb, 0x14, 0x1a, 0xa0, 0x2d, 0xc4, 0x24, 0x33, 0xea, 0xd2, 0x6d,
	0x09, 0x5d, 0x21, 0x2a, 0x44, 0xfc, 0x1b, 0xc0, 0x3d, 0xbe, 0xe8, 0xa7, 0x64, 0x54, 0xac, 0x8c,
	0x42, 0x84, 0xd6, 0x37, 0x6a, 0x46, 0x1c, 0xb0, 0x27, 0xf9, 0x1b, 0x05, 0xf4, 0x9e, 0x92, 0xd6,
	0xea, 0x05, 0x9d, 0x66, 0x45, 0x6a, 0x38, 0x54, 0x4b, 0x36, 0x30, 0x7c, 0x07, 0xe0, 0x5c, 0x69,
	0x9f, 0x3b, 0x47, 0x5a, 0xca, 0xb3, 0xb6, 0x8c, 0x43, 0xe8, 0x46, 0xc9, 0x2f, 0xf4, 0x75, 0xea,
	0x78, 0xb5, 0xd8, 0x5f, 0x1d, 0xc2, 0x43, 0xc0, 0xb3, 0x82, 0xb4, 0xa6, 0xf8, 0x34, 0x4b, 0x0d,
	0xa5, 0x66, 0x72, 0x3d, 0x27, 0xdf, 0x4d, 0x37, 0xac, 0x88, 0xf7, 0x60, 0xf7, 0x3c, 0xd1, 0x86,
	0x73, 0x59, 0xb4, 0x01, 0x37, 0x2f, 0x5f, 0x98, 0x4f, 0xa7, 0x34, 0xc5, 0x18, 0xb0, 0xbe, 0xdd,
	0x57, 0xfc, 0x18, 0xb6, 0x1b, 0xc5, 0x28, 0xef, 0x0b, 0x39, 0x8f, 0xc6, 0x92, 0x5c, 0xda, 0x29,
	0xde, 0x85, 0xfe, 0x19, 0xdd, 0x3a, 0xfe, 0x31, 0x77, 0xed, 0x52, 0xf8, 0x5b, 0xf6, 0xc9, 0x15,
	0x40, 0x14, 0x4d, 0xca, 0x18, 0xf6, 0xa9, 0x99, 0x9c, 0xd4, 0x8c, 0x43, 0xd8, 0xa7, 0xc6, 0x96,
	0x6d, 0xd0, 0xe8, 0x42, 0xe5, 0xb1, 0xbf, 0x2c, 0x67, 0xd8, 0x96, 0x9e, 0x64, 0xfe, 0x59, 0x84,
	0xbc, 0xb0, 0xb0, 0x97, 0x1e, 0x8d, 0xbb, 0x93, 0x1a, 0x22, 0x46, 0xd0, 0xe7, 0xb8, 0x8e, 0xed,
	0xe9, 0x45, 0x91, 0xfe, 0x64, 0xa3, 0xf0, 0x87, 0xcf, 0xcf, 0x19, 0xe2, 0x47, 0xe8, 0xba, 0x4e,
	0xbe, 0x0b, 0x45, 0xdb, 0xf6, 0x59, 0x91, 0x4f, 0xe9, 0x3b, 0x79, 0xce, 0x1c, 0x3b, 0xb2, 0x02,
	0xc4, 0x14, 0xba, 0x8f, 0x8b, 0xd9, 0xfc, 0x6e, 0xae, 0xdf, 0x86, 0xed, 0xc7, 0xa4, 0x4d, 0x92,
	0x2a, 0x93, 0x64, 0x69, 0xe5, 0x7f, 0x09, 0xb5, 0x2f, 0xd1, 0x05, 0xf9, 0x1f, 0x5f, 0xe2, 0x47,
	0xb0, 0xfd, 0xe5, 0x15, 0xa5, 0xe6, 0xc4, 0x98, 0x3c, 0x79, 0x56, 0x18, 0xc2, 0x3e, 0x84, 0x4f,
	0xe8, 0xda, 0x27, 0x66, 0x3f, 0x6d, 0x56, 0xdf, 0xab, 0xcb, 0x82, 0x38, 0x42, 0x47, 0x3a, 0x43,
	0xfc, 0x1d, 0xc0, 0x06, 0x1f, 0x7d, 0x89, 0xc0, 0xef, 0x43, 0x7b, 0x42, 0xa9, 0xf2, 0xef, 0xb7,
	0x23, 0xbd, 0x65, 0xbb, 0x34, 0xa2, 0xfc, 0x2a, 0x99, 0x92, 0x2f, 0x47, 0x69, 0x5a, 0x2d, 0x78,
	0x92, 0xa4, 0x4e, 0xde, 0x3b, 0x92, 0xbf, 0xf1, 0x11, 0xc0, 0x82, 0xa2, 0x1e, 0x6c, 0x70, 0x9f,
	0xbe, 0xc6, 0x7d, 0xda, 0xa4, 0x2f, 0x6b, 0xdb, 0xc4, 0x3f, 0x01, 0xec, 0x8c, 0x0b, 0xc3, 0x3b,
	0xca, 0xab, 0x7b, 0x65, 0xc9, 0x22, 0xf4, 0x2b, 0xae, 0x7e, 0xcc, 0xfc, 0x16, 0xc0, 0xce, 0x19,
	0x35, 0x13, 0xa8, 0x28, 0x06, 0x0d, 0x8a, 0xcd, 0x77, 0xb4, 0xfe, 0xf2, 0xe1, 0x13, 0xde, 0x34,
	0x7c, 0x6e, 0x1e, 0x30, 0x1f, 0xb2, 0xca, 0x34, 0xb8, 0xa1, 0x80, 0x36, 0x03, 0xa5, 0x6a, 0x40,
	0x95, 0xa0, 0xf4, 0x2b, 0x47, 0x7f, 0xae, 0xc3, 0x96, 0x97, 0x6b, 0x8d, 0x9f, 0x03, 0x54, 0x93,
	0x14, 0xf7, 0x79, 0xfb, 0xca, 0x58, 0x3e, 0x78, 0x7d, 0x05, 0xf7, 0xb5, 0x58, 0xc3, 0x13, 0x80,
	0x6a, 0xcc, 0x79, 0x07, 0x2b, 0x43, 0xd8, 0x3b, 0x58, 0x9d, 0x87, 0x62, 0xed, 0xfd, 0xc0, 0x72,
	0xa8, 0x04, 0xd8, 0xbb, 0x58, 0x11, 0x70, 0xef, 0x62, 0x55, 0xa9, 0xc5, 0x1a, 0x7e, 0x06, 0x9d,
	0x85, 0x82, 0xe2, 0xfd, 0x32, 0x54, 0xf3, 0xf8, 0xfe, 0x32, 0x5c, 0x11, 0x38, 0xfa, 0x2b, 0x80,
	0x4d, 0x27, 0x16, 0x1a, 0x1f, 0x42, 0xcb, 0xea, 0x15, 0xf6, 0x5d, 0xb8, 0x4a, 0xba, 0x0e, 0x76,
	0x6b, 0x48, 0x8d, 0xfd, 0x07, 0x10, 0x46, 0xd1, 0x04, 0x77, 0x78, 0xb5, 0x12, 0xe3, 0x83, 0xfb,
	0x15, 0x50, 0x53, 0x49, 0x3e, 0xf2, 0x10, 0x5a, 0x56, 0x53, 0x7c, 0x8c, 0x9a, 0x86, 0xf9, 0x18,
	0x75, 0xc1, 0x61, 0x82, 0xbf, 0x06, 0xe5, 0xbd, 0xe2, 0xc7, 0xb0, 0x55, 0x76, 0x24, 0xee, 0x95,
	0xd7, 0x52, 0xef, 0x45, 0x1f, 0x78, 0xa5, 0x6d, 0xd7, 0xf0, 0x53, 0x2e, 0x93, 0xf7, 0xb3, 0x57,
	0xd6, 0xe3, 0x86, 0xb3, 0xcb, 0x6d, 0x65, 0x39, 0x3c, 0x6b, 0xf3, 0x8f, 0xe4, 0xa3, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x7d, 0x4c, 0xed, 0x93, 0x56, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessagesClient is the client API for Messages service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessagesClient interface {
	PutRecords(ctx context.Context, in *PutRecordsRequest, opts ...grpc.CallOption) (*PutRecordsResponse, error)
	GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (Messages_GetRecordsClient, error)
	ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error)
	GetTopics(ctx context.Context, in *GetTopicsRequest, opts ...grpc.CallOption) (Messages_GetTopicsClient, error)
}

type messagesClient struct {
	cc *grpc.ClientConn
}

func NewMessagesClient(cc *grpc.ClientConn) MessagesClient {
	return &messagesClient{cc}
}

func (c *messagesClient) PutRecords(ctx context.Context, in *PutRecordsRequest, opts ...grpc.CallOption) (*PutRecordsResponse, error) {
	out := new(PutRecordsResponse)
	err := c.cc.Invoke(ctx, "/api.Messages/PutRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesClient) GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (Messages_GetRecordsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Messages_serviceDesc.Streams[0], "/api.Messages/GetRecords", opts...)
	if err != nil {
		return nil, err
	}
	x := &messagesGetRecordsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Messages_GetRecordsClient interface {
	Recv() (*GetRecordsResponse, error)
	grpc.ClientStream
}

type messagesGetRecordsClient struct {
	grpc.ClientStream
}

func (x *messagesGetRecordsClient) Recv() (*GetRecordsResponse, error) {
	m := new(GetRecordsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messagesClient) ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error) {
	out := new(ListTopicsResponse)
	err := c.cc.Invoke(ctx, "/api.Messages/ListTopics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesClient) GetTopics(ctx context.Context, in *GetTopicsRequest, opts ...grpc.CallOption) (Messages_GetTopicsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Messages_serviceDesc.Streams[1], "/api.Messages/GetTopics", opts...)
	if err != nil {
		return nil, err
	}
	x := &messagesGetTopicsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Messages_GetTopicsClient interface {
	Recv() (*GetTopicsResponse, error)
	grpc.ClientStream
}

type messagesGetTopicsClient struct {
	grpc.ClientStream
}

func (x *messagesGetTopicsClient) Recv() (*GetTopicsResponse, error) {
	m := new(GetTopicsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessagesServer is the server API for Messages service.
type MessagesServer interface {
	PutRecords(context.Context, *PutRecordsRequest) (*PutRecordsResponse, error)
	GetRecords(*GetRecordsRequest, Messages_GetRecordsServer) error
	ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error)
	GetTopics(*GetTopicsRequest, Messages_GetTopicsServer) error
}

// UnimplementedMessagesServer can be embedded to have forward compatible implementations.
type UnimplementedMessagesServer struct {
}

func (*UnimplementedMessagesServer) PutRecords(ctx context.Context, req *PutRecordsRequest) (*PutRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutRecords not implemented")
}
func (*UnimplementedMessagesServer) GetRecords(req *GetRecordsRequest, srv Messages_GetRecordsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRecords not implemented")
}
func (*UnimplementedMessagesServer) ListTopics(ctx context.Context, req *ListTopicsRequest) (*ListTopicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopics not implemented")
}
func (*UnimplementedMessagesServer) GetTopics(req *GetTopicsRequest, srv Messages_GetTopicsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTopics not implemented")
}

func RegisterMessagesServer(s *grpc.Server, srv MessagesServer) {
	s.RegisterService(&_Messages_serviceDesc, srv)
}

func _Messages_PutRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServer).PutRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Messages/PutRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServer).PutRecords(ctx, req.(*PutRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messages_GetRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRecordsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessagesServer).GetRecords(m, &messagesGetRecordsServer{stream})
}

type Messages_GetRecordsServer interface {
	Send(*GetRecordsResponse) error
	grpc.ServerStream
}

type messagesGetRecordsServer struct {
	grpc.ServerStream
}

func (x *messagesGetRecordsServer) Send(m *GetRecordsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Messages_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Messages/ListTopics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServer).ListTopics(ctx, req.(*ListTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messages_GetTopics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTopicsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessagesServer).GetTopics(m, &messagesGetTopicsServer{stream})
}

type Messages_GetTopicsServer interface {
	Send(*GetTopicsResponse) error
	grpc.ServerStream
}

type messagesGetTopicsServer struct {
	grpc.ServerStream
}

func (x *messagesGetTopicsServer) Send(m *GetTopicsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Messages_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Messages",
	HandlerType: (*MessagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutRecords",
			Handler:    _Messages_PutRecords_Handler,
		},
		{
			MethodName: "ListTopics",
			Handler:    _Messages_ListTopics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRecords",
			Handler:       _Messages_GetRecords_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTopics",
			Handler:       _Messages_GetTopics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nest.proto",
}

// StreamsClient is the client API for Streams service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamsClient interface {
	Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (Streams_LoadClient, error)
	SST(ctx context.Context, in *SSTRequest, opts ...grpc.CallOption) (Streams_SSTClient, error)
	Dump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (Streams_DumpClient, error)
}

type streamsClient struct {
	cc *grpc.ClientConn
}

func NewStreamsClient(cc *grpc.ClientConn) StreamsClient {
	return &streamsClient{cc}
}

func (c *streamsClient) Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (Streams_LoadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Streams_serviceDesc.Streams[0], "/api.Streams/Load", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamsLoadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Streams_LoadClient interface {
	Recv() (*LoadResponse, error)
	grpc.ClientStream
}

type streamsLoadClient struct {
	grpc.ClientStream
}

func (x *streamsLoadClient) Recv() (*LoadResponse, error) {
	m := new(LoadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamsClient) SST(ctx context.Context, in *SSTRequest, opts ...grpc.CallOption) (Streams_SSTClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Streams_serviceDesc.Streams[1], "/api.Streams/SST", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamsSSTClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Streams_SSTClient interface {
	Recv() (*SSTResponseChunk, error)
	grpc.ClientStream
}

type streamsSSTClient struct {
	grpc.ClientStream
}

func (x *streamsSSTClient) Recv() (*SSTResponseChunk, error) {
	m := new(SSTResponseChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamsClient) Dump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (Streams_DumpClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Streams_serviceDesc.Streams[2], "/api.Streams/Dump", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamsDumpClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Streams_DumpClient interface {
	Recv() (*DumpResponse, error)
	grpc.ClientStream
}

type streamsDumpClient struct {
	grpc.ClientStream
}

func (x *streamsDumpClient) Recv() (*DumpResponse, error) {
	m := new(DumpResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamsServer is the server API for Streams service.
type StreamsServer interface {
	Load(*LoadRequest, Streams_LoadServer) error
	SST(*SSTRequest, Streams_SSTServer) error
	Dump(*DumpRequest, Streams_DumpServer) error
}

// UnimplementedStreamsServer can be embedded to have forward compatible implementations.
type UnimplementedStreamsServer struct {
}

func (*UnimplementedStreamsServer) Load(req *LoadRequest, srv Streams_LoadServer) error {
	return status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (*UnimplementedStreamsServer) SST(req *SSTRequest, srv Streams_SSTServer) error {
	return status.Errorf(codes.Unimplemented, "method SST not implemented")
}
func (*UnimplementedStreamsServer) Dump(req *DumpRequest, srv Streams_DumpServer) error {
	return status.Errorf(codes.Unimplemented, "method Dump not implemented")
}

func RegisterStreamsServer(s *grpc.Server, srv StreamsServer) {
	s.RegisterService(&_Streams_serviceDesc, srv)
}

func _Streams_Load_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamsServer).Load(m, &streamsLoadServer{stream})
}

type Streams_LoadServer interface {
	Send(*LoadResponse) error
	grpc.ServerStream
}

type streamsLoadServer struct {
	grpc.ServerStream
}

func (x *streamsLoadServer) Send(m *LoadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Streams_SST_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SSTRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamsServer).SST(m, &streamsSSTServer{stream})
}

type Streams_SSTServer interface {
	Send(*SSTResponseChunk) error
	grpc.ServerStream
}

type streamsSSTServer struct {
	grpc.ServerStream
}

func (x *streamsSSTServer) Send(m *SSTResponseChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _Streams_Dump_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DumpRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamsServer).Dump(m, &streamsDumpServer{stream})
}

type Streams_DumpServer interface {
	Send(*DumpResponse) error
	grpc.ServerStream
}

type streamsDumpServer struct {
	grpc.ServerStream
}

func (x *streamsDumpServer) Send(m *DumpResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Streams_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Streams",
	HandlerType: (*StreamsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Load",
			Handler:       _Streams_Load_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SST",
			Handler:       _Streams_SST_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Dump",
			Handler:       _Streams_Dump_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nest.proto",
}

// EventsClient is the client API for Events service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventsClient interface {
	PutEvent(ctx context.Context, in *PutEventRequest, opts ...grpc.CallOption) (*PutEventResponse, error)
	GetEvents(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (Events_GetEventsClient, error)
}

type eventsClient struct {
	cc *grpc.ClientConn
}

func NewEventsClient(cc *grpc.ClientConn) EventsClient {
	return &eventsClient{cc}
}

func (c *eventsClient) PutEvent(ctx context.Context, in *PutEventRequest, opts ...grpc.CallOption) (*PutEventResponse, error) {
	out := new(PutEventResponse)
	err := c.cc.Invoke(ctx, "/api.Events/PutEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsClient) GetEvents(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (Events_GetEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Events_serviceDesc.Streams[0], "/api.Events/GetEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventsGetEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Events_GetEventsClient interface {
	Recv() (*GetEventResponse, error)
	grpc.ClientStream
}

type eventsGetEventsClient struct {
	grpc.ClientStream
}

func (x *eventsGetEventsClient) Recv() (*GetEventResponse, error) {
	m := new(GetEventResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EventsServer is the server API for Events service.
type EventsServer interface {
	PutEvent(context.Context, *PutEventRequest) (*PutEventResponse, error)
	GetEvents(*GetEventRequest, Events_GetEventsServer) error
}

// UnimplementedEventsServer can be embedded to have forward compatible implementations.
type UnimplementedEventsServer struct {
}

func (*UnimplementedEventsServer) PutEvent(ctx context.Context, req *PutEventRequest) (*PutEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutEvent not implemented")
}
func (*UnimplementedEventsServer) GetEvents(req *GetEventRequest, srv Events_GetEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}

func RegisterEventsServer(s *grpc.Server, srv EventsServer) {
	s.RegisterService(&_Events_serviceDesc, srv)
}

func _Events_PutEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServer).PutEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Events/PutEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServer).PutEvent(ctx, req.(*PutEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Events_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventsServer).GetEvents(m, &eventsGetEventsServer{stream})
}

type Events_GetEventsServer interface {
	Send(*GetEventResponse) error
	grpc.ServerStream
}

type eventsGetEventsServer struct {
	grpc.ServerStream
}

func (x *eventsGetEventsServer) Send(m *GetEventResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Events_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Events",
	HandlerType: (*EventsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutEvent",
			Handler:    _Events_PutEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvents",
			Handler:       _Events_GetEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nest.proto",
}
