// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package fsm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/vx-labs/nest/nest/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PeerLost struct {
	Peer                 uint64   `protobuf:"varint,1,opt,name=Peer,proto3" json:"Peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerLost) Reset()         { *m = PeerLost{} }
func (m *PeerLost) String() string { return proto.CompactTextString(m) }
func (*PeerLost) ProtoMessage()    {}
func (*PeerLost) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *PeerLost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerLost.Unmarshal(m, b)
}
func (m *PeerLost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerLost.Marshal(b, m, deterministic)
}
func (m *PeerLost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerLost.Merge(m, src)
}
func (m *PeerLost) XXX_Size() int {
	return xxx_messageInfo_PeerLost.Size(m)
}
func (m *PeerLost) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerLost.DiscardUnknown(m)
}

var xxx_messageInfo_PeerLost proto.InternalMessageInfo

func (m *PeerLost) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

type PeerJoined struct {
	Peer                 uint64   `protobuf:"varint,1,opt,name=Peer,proto3" json:"Peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerJoined) Reset()         { *m = PeerJoined{} }
func (m *PeerJoined) String() string { return proto.CompactTextString(m) }
func (*PeerJoined) ProtoMessage()    {}
func (*PeerJoined) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *PeerJoined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerJoined.Unmarshal(m, b)
}
func (m *PeerJoined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerJoined.Marshal(b, m, deterministic)
}
func (m *PeerJoined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerJoined.Merge(m, src)
}
func (m *PeerJoined) XXX_Size() int {
	return xxx_messageInfo_PeerJoined.Size(m)
}
func (m *PeerJoined) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerJoined.DiscardUnknown(m)
}

var xxx_messageInfo_PeerJoined proto.InternalMessageInfo

func (m *PeerJoined) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

type ShardReplicas struct {
	Peer                 uint64   `protobuf:"varint,1,opt,name=Peer,proto3" json:"Peer,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardReplicas) Reset()         { *m = ShardReplicas{} }
func (m *ShardReplicas) String() string { return proto.CompactTextString(m) }
func (*ShardReplicas) ProtoMessage()    {}
func (*ShardReplicas) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *ShardReplicas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardReplicas.Unmarshal(m, b)
}
func (m *ShardReplicas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardReplicas.Marshal(b, m, deterministic)
}
func (m *ShardReplicas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardReplicas.Merge(m, src)
}
func (m *ShardReplicas) XXX_Size() int {
	return xxx_messageInfo_ShardReplicas.Size(m)
}
func (m *ShardReplicas) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardReplicas.DiscardUnknown(m)
}

var xxx_messageInfo_ShardReplicas proto.InternalMessageInfo

func (m *ShardReplicas) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

func (m *ShardReplicas) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ShardMetadata struct {
	ID                   uint64           `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Leader               uint64           `protobuf:"varint,2,opt,name=Leader,proto3" json:"Leader,omitempty"`
	Replicas             []*ShardReplicas `protobuf:"bytes,3,rep,name=Replicas,proto3" json:"Replicas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ShardMetadata) Reset()         { *m = ShardMetadata{} }
func (m *ShardMetadata) String() string { return proto.CompactTextString(m) }
func (*ShardMetadata) ProtoMessage()    {}
func (*ShardMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *ShardMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardMetadata.Unmarshal(m, b)
}
func (m *ShardMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardMetadata.Marshal(b, m, deterministic)
}
func (m *ShardMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardMetadata.Merge(m, src)
}
func (m *ShardMetadata) XXX_Size() int {
	return xxx_messageInfo_ShardMetadata.Size(m)
}
func (m *ShardMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ShardMetadata proto.InternalMessageInfo

func (m *ShardMetadata) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ShardMetadata) GetLeader() uint64 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *ShardMetadata) GetReplicas() []*ShardReplicas {
	if m != nil {
		return m.Replicas
	}
	return nil
}

type ShardLeadershipAssigned struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	NewLeader            uint64   `protobuf:"varint,2,opt,name=NewLeader,proto3" json:"NewLeader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardLeadershipAssigned) Reset()         { *m = ShardLeadershipAssigned{} }
func (m *ShardLeadershipAssigned) String() string { return proto.CompactTextString(m) }
func (*ShardLeadershipAssigned) ProtoMessage()    {}
func (*ShardLeadershipAssigned) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *ShardLeadershipAssigned) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardLeadershipAssigned.Unmarshal(m, b)
}
func (m *ShardLeadershipAssigned) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardLeadershipAssigned.Marshal(b, m, deterministic)
}
func (m *ShardLeadershipAssigned) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardLeadershipAssigned.Merge(m, src)
}
func (m *ShardLeadershipAssigned) XXX_Size() int {
	return xxx_messageInfo_ShardLeadershipAssigned.Size(m)
}
func (m *ShardLeadershipAssigned) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardLeadershipAssigned.DiscardUnknown(m)
}

var xxx_messageInfo_ShardLeadershipAssigned proto.InternalMessageInfo

func (m *ShardLeadershipAssigned) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ShardLeadershipAssigned) GetNewLeader() uint64 {
	if m != nil {
		return m.NewLeader
	}
	return 0
}

type ShardReplicaProgressed struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Peer                 uint64   `protobuf:"varint,2,opt,name=Peer,proto3" json:"Peer,omitempty"`
	Offset               uint64   `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardReplicaProgressed) Reset()         { *m = ShardReplicaProgressed{} }
func (m *ShardReplicaProgressed) String() string { return proto.CompactTextString(m) }
func (*ShardReplicaProgressed) ProtoMessage()    {}
func (*ShardReplicaProgressed) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *ShardReplicaProgressed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardReplicaProgressed.Unmarshal(m, b)
}
func (m *ShardReplicaProgressed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardReplicaProgressed.Marshal(b, m, deterministic)
}
func (m *ShardReplicaProgressed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardReplicaProgressed.Merge(m, src)
}
func (m *ShardReplicaProgressed) XXX_Size() int {
	return xxx_messageInfo_ShardReplicaProgressed.Size(m)
}
func (m *ShardReplicaProgressed) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardReplicaProgressed.DiscardUnknown(m)
}

var xxx_messageInfo_ShardReplicaProgressed proto.InternalMessageInfo

func (m *ShardReplicaProgressed) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ShardReplicaProgressed) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

func (m *ShardReplicaProgressed) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type StateTransitionSet struct {
	Events               []*StateTransition `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StateTransitionSet) Reset()         { *m = StateTransitionSet{} }
func (m *StateTransitionSet) String() string { return proto.CompactTextString(m) }
func (*StateTransitionSet) ProtoMessage()    {}
func (*StateTransitionSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *StateTransitionSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateTransitionSet.Unmarshal(m, b)
}
func (m *StateTransitionSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateTransitionSet.Marshal(b, m, deterministic)
}
func (m *StateTransitionSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateTransitionSet.Merge(m, src)
}
func (m *StateTransitionSet) XXX_Size() int {
	return xxx_messageInfo_StateTransitionSet.Size(m)
}
func (m *StateTransitionSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StateTransitionSet.DiscardUnknown(m)
}

var xxx_messageInfo_StateTransitionSet proto.InternalMessageInfo

func (m *StateTransitionSet) GetEvents() []*StateTransition {
	if m != nil {
		return m.Events
	}
	return nil
}

type StateTransition struct {
	// Types that are valid to be assigned to Event:
	//	*StateTransition_PeerLost
	//	*StateTransition_PeerJoined
	//	*StateTransition_ShardReplicaProgressed
	//	*StateTransition_ShardLeadershipAssigned
	Event                isStateTransition_Event `protobuf_oneof:"Event"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *StateTransition) Reset()         { *m = StateTransition{} }
func (m *StateTransition) String() string { return proto.CompactTextString(m) }
func (*StateTransition) ProtoMessage()    {}
func (*StateTransition) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *StateTransition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateTransition.Unmarshal(m, b)
}
func (m *StateTransition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateTransition.Marshal(b, m, deterministic)
}
func (m *StateTransition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateTransition.Merge(m, src)
}
func (m *StateTransition) XXX_Size() int {
	return xxx_messageInfo_StateTransition.Size(m)
}
func (m *StateTransition) XXX_DiscardUnknown() {
	xxx_messageInfo_StateTransition.DiscardUnknown(m)
}

var xxx_messageInfo_StateTransition proto.InternalMessageInfo

type isStateTransition_Event interface {
	isStateTransition_Event()
}

type StateTransition_PeerLost struct {
	PeerLost *PeerLost `protobuf:"bytes,1,opt,name=PeerLost,proto3,oneof"`
}

type StateTransition_PeerJoined struct {
	PeerJoined *PeerJoined `protobuf:"bytes,2,opt,name=PeerJoined,proto3,oneof"`
}

type StateTransition_ShardReplicaProgressed struct {
	ShardReplicaProgressed *ShardReplicaProgressed `protobuf:"bytes,3,opt,name=ShardReplicaProgressed,proto3,oneof"`
}

type StateTransition_ShardLeadershipAssigned struct {
	ShardLeadershipAssigned *ShardLeadershipAssigned `protobuf:"bytes,4,opt,name=ShardLeadershipAssigned,proto3,oneof"`
}

func (*StateTransition_PeerLost) isStateTransition_Event() {}

func (*StateTransition_PeerJoined) isStateTransition_Event() {}

func (*StateTransition_ShardReplicaProgressed) isStateTransition_Event() {}

func (*StateTransition_ShardLeadershipAssigned) isStateTransition_Event() {}

func (m *StateTransition) GetEvent() isStateTransition_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *StateTransition) GetPeerLost() *PeerLost {
	if x, ok := m.GetEvent().(*StateTransition_PeerLost); ok {
		return x.PeerLost
	}
	return nil
}

func (m *StateTransition) GetPeerJoined() *PeerJoined {
	if x, ok := m.GetEvent().(*StateTransition_PeerJoined); ok {
		return x.PeerJoined
	}
	return nil
}

func (m *StateTransition) GetShardReplicaProgressed() *ShardReplicaProgressed {
	if x, ok := m.GetEvent().(*StateTransition_ShardReplicaProgressed); ok {
		return x.ShardReplicaProgressed
	}
	return nil
}

func (m *StateTransition) GetShardLeadershipAssigned() *ShardLeadershipAssigned {
	if x, ok := m.GetEvent().(*StateTransition_ShardLeadershipAssigned); ok {
		return x.ShardLeadershipAssigned
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StateTransition) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StateTransition_PeerLost)(nil),
		(*StateTransition_PeerJoined)(nil),
		(*StateTransition_ShardReplicaProgressed)(nil),
		(*StateTransition_ShardLeadershipAssigned)(nil),
	}
}

func init() {
	proto.RegisterType((*PeerLost)(nil), "fsm.PeerLost")
	proto.RegisterType((*PeerJoined)(nil), "fsm.PeerJoined")
	proto.RegisterType((*ShardReplicas)(nil), "fsm.ShardReplicas")
	proto.RegisterType((*ShardMetadata)(nil), "fsm.ShardMetadata")
	proto.RegisterType((*ShardLeadershipAssigned)(nil), "fsm.ShardLeadershipAssigned")
	proto.RegisterType((*ShardReplicaProgressed)(nil), "fsm.ShardReplicaProgressed")
	proto.RegisterType((*StateTransitionSet)(nil), "fsm.StateTransitionSet")
	proto.RegisterType((*StateTransition)(nil), "fsm.StateTransition")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x5f, 0xef, 0xd2, 0x30,
	0x14, 0x1d, 0x1b, 0x22, 0xde, 0x05, 0x49, 0x1a, 0x83, 0x8b, 0x12, 0x43, 0xf6, 0x44, 0xfc, 0x33,
	0xe2, 0x7c, 0xf4, 0x49, 0x82, 0x71, 0x18, 0x54, 0x52, 0x30, 0xf1, 0xb5, 0xb0, 0xbb, 0xd1, 0x04,
	0xb6, 0x65, 0xad, 0xa8, 0x9f, 0xc9, 0x2f, 0xf9, 0xcb, 0xba, 0x8d, 0x31, 0xd8, 0x1e, 0xb6, 0xb6,
	0xb7, 0xe7, 0xdc, 0x3f, 0xe7, 0x14, 0x4c, 0xf9, 0x2f, 0x41, 0xe1, 0x24, 0x69, 0x2c, 0x63, 0x62,
	0x04, 0xe2, 0xf4, 0xe2, 0x75, 0xc8, 0xe5, 0xe1, 0xf7, 0xce, 0xd9, 0xc7, 0xa7, 0xd9, 0xf9, 0xef,
	0xbb, 0x23, 0xdb, 0x89, 0x59, 0x84, 0x42, 0xe6, 0x3f, 0x96, 0xf0, 0xec, 0xcb, 0x09, 0xf6, 0x2b,
	0xe8, 0xaf, 0x11, 0xd3, 0x55, 0x2c, 0x24, 0x21, 0xd0, 0xcd, 0xf6, 0x56, 0x67, 0xd2, 0x99, 0x76,
	0xa9, 0xda, 0xdb, 0x13, 0x80, 0x6c, 0xfd, 0x1a, 0xf3, 0x08, 0xfd, 0x46, 0xc4, 0x47, 0x18, 0x6c,
	0x0e, 0x2c, 0xf5, 0x29, 0x26, 0x47, 0xbe, 0x67, 0xa2, 0x09, 0x44, 0x46, 0xd0, 0xfb, 0x11, 0x04,
	0x02, 0xa5, 0xa5, 0xab, 0x68, 0x71, 0xb2, 0xc3, 0x82, 0xfc, 0x0d, 0x25, 0xf3, 0x99, 0x64, 0xe4,
	0x29, 0xe8, 0xcb, 0x45, 0x41, 0xd5, 0x97, 0x8b, 0x8c, 0xb8, 0x42, 0xe6, 0x63, 0x5a, 0x12, 0xf3,
	0x13, 0x71, 0xa0, 0x5f, 0x16, 0xb4, 0x8c, 0x89, 0x31, 0x35, 0x5d, 0xe2, 0x04, 0xe2, 0xe4, 0xd4,
	0x5a, 0xa1, 0x17, 0x8c, 0xfd, 0x05, 0x9e, 0xab, 0xab, 0x9c, 0x2e, 0x0e, 0x3c, 0xf9, 0x24, 0x04,
	0x0f, 0xb3, 0xa1, 0x6e, 0x4b, 0x8e, 0xe1, 0xc9, 0x77, 0xfc, 0x53, 0xab, 0x5a, 0x05, 0xec, 0x2d,
	0x8c, 0xae, 0x6b, 0xac, 0xd3, 0x38, 0x4c, 0x51, 0x88, 0x86, 0x3c, 0xa5, 0x0e, 0x7a, 0xa3, 0x0e,
	0x46, 0x4d, 0x87, 0x39, 0x90, 0x8d, 0x64, 0x12, 0xb7, 0x29, 0x8b, 0x04, 0x97, 0x3c, 0x8e, 0x36,
	0x28, 0xc9, 0x5b, 0xe8, 0xe1, 0x19, 0x23, 0x29, 0xac, 0x8e, 0x1a, 0xf1, 0x59, 0x3e, 0x62, 0x1d,
	0x48, 0x0b, 0x8c, 0xfd, 0x5f, 0x87, 0xe1, 0xcd, 0x1d, 0x79, 0x53, 0xd9, 0xab, 0x3a, 0x33, 0xdd,
	0x81, 0xca, 0x51, 0x06, 0x3d, 0x8d, 0x56, 0xfe, 0xbf, 0xbf, 0xf6, 0x5a, 0xb5, 0x6d, 0xba, 0xc3,
	0x0b, 0x3c, 0x0f, 0x7b, 0x1a, 0xbd, 0x7e, 0x10, 0x3f, 0xdb, 0xd4, 0x50, 0xf3, 0x99, 0xee, 0xcb,
	0x3b, 0x53, 0x2a, 0x88, 0xa7, 0xd1, 0x36, 0x29, 0x7f, 0xb5, 0xba, 0x65, 0x75, 0x55, 0xde, 0x71,
	0x95, 0xf7, 0x1e, 0xe3, 0x69, 0xb4, 0x8d, 0x3e, 0x7f, 0x0c, 0x8f, 0x3e, 0x67, 0x72, 0xed, 0x7a,
	0xea, 0xfd, 0x7f, 0x78, 0x08, 0x00, 0x00, 0xff, 0xff, 0x00, 0x73, 0x9e, 0xfa, 0x3f, 0x03, 0x00,
	0x00,
}
